=begin
#Klaviyo API

#Empowering creators to own their destiny

The version of the OpenAPI document: 2022.03.29

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

# Common files
require 'klaviyo_sdk/api_client'
require 'klaviyo_sdk/api_error'
require 'klaviyo_sdk/version'
require 'klaviyo_sdk/configuration'

# APIs
require 'klaviyo_sdk/api/campaigns_api'
require 'klaviyo_sdk/api/data_privacy_api'
require 'klaviyo_sdk/api/lists_segments_api'
require 'klaviyo_sdk/api/metrics_api'
require 'klaviyo_sdk/api/profiles_api'
require 'klaviyo_sdk/api/templates_api'
require 'klaviyo_sdk/api/track_identify_api'

# retry logic
require 'retriable'

module Klaviyo
  @is_initialized = false

  class << self
    # Customize default settings for the SDK using block.
    #   Klaviyo.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.

 
    # add retriable config
    # todo: check how slow this is
    Configuration.default.class.module_eval { attr_accessor :max_retries, :max_delay }

    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end

      # create wrapper classes
      if !@is_initialized # run this only once
        self.constants.each do |c|
          if c[-3..-1] == "Api"
            attributes = [:attr1]
            wrapper_class = Klaviyo.const_set(c[0..-4], Struct.new(*attributes))
            original_class = Klaviyo.const_get(c)
            
            # recreate methods
            original_class.public_instance_methods(false).each do |m|
              wrapper_class.class_eval { 
                define_singleton_method m do |*arg| 
                  # max_delay=60, max_retries=3
                  # retry_codes = [429,503,504]
                  # only add retriable if both of these are not set
                  max_retries = Configuration.default.max_retries
                  max_delay = Configuration.default.max_delay

                  if (max_retries != nil && max_delay != nil)
                    Retriable.configure do |c|
                      c.tries = max_retries
                      c.max_elapsed_time = max_delay
                      c.on = {
                        Klaviyo::ApiError => [/429/, /503/, /504/]
                      }
                    end
                    Retriable.retriable do
                      Klaviyo.const_get(c).new.send(m, *arg)
                    end
                  else
                    Klaviyo.const_get(c).new.send(m, *arg)
                  end
                end
              }
            end
          end
        end
        @is_initialized = true
      end
    end
  end
end
